import { useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { commandCenterDashboard, resolveCommandPeriod, type CommandPeriodKey, type DashboardMetric, type TrendPoint } from './commandCenter'
import { durationMinutes, localDateKey, titleFor, type RecordData } from './model'

type TargetView = 'projects' | 'outcomes' | 'finance' | 'decisions' | 'notebook' | 'time'
type Props = { records: RecordData[]; onOpen: (record: RecordData) => void; onView: (view: TargetView) => void; onRefresh: () => Promise<void> }
const money = (minor: bigint) => `¥${Math.round(Number(minor) / 100).toLocaleString('zh-CN')}`
const minutes = (value: number) => value < 60 ? `${Math.round(value)}m` : `${Math.round(value / 6) / 10}h`
const dueKey = (record: RecordData) => { const raw = String(record.reviewDueDate || record.expectedCompletionDate || record.date || ''); return /^\d{4}-\d{2}-\d{2}/.test(raw) ? raw.slice(0, 10) : localDateKey(raw) }
const periodOptions: { key: CommandPeriodKey; label: string }[] = [{ key: '7d', label: '近 7 天' }, { key: '30d', label: '近 30 天' }, { key: 'quarter', label: '本季度' }, { key: 'year', label: '本年度' }, { key: 'custom', label: '自定义' }]

function Sparkline({ values, tone = 'green' }: { values: number[]; tone?: 'green' | 'blue' | 'orange' | 'purple' }) {
  const valid = values.filter(Number.isFinite); if (valid.length < 2) return <span className="ceo-no-trend">暂无趋势</span>
  const max = Math.max(...valid); const min = Math.min(...valid); const range = max - min || 1
  const points = values.map((value, index) => `${index / (values.length - 1) * 100},${32 - (value - min) / range * 26}`).join(' ')
  return <svg className={`ceo-sparkline ${tone}`} viewBox="0 0 100 36" preserveAspectRatio="none" aria-label="趋势"><polyline points={points} fill="none" vectorEffect="non-scaling-stroke" /></svg>
}

function MetricCard({ metric, onClick, values, tone }: { metric: DashboardMetric; onClick: () => void; values: number[]; tone: 'green' | 'blue' | 'orange' | 'purple' }) {
  return <button className={`ceo-kpi ${metric.tone || 'neutral'}`} onClick={onClick} title={metric.formula}><span>{metric.label}</span><strong>{metric.value}</strong><small className={metric.delta === null ? '' : metric.delta >= 0 ? 'up' : 'down'}>{metric.delta === null ? metric.hint : `${metric.delta >= 0 ? '↑' : '↓'} ${Math.abs(metric.delta).toLocaleString()} vs 上期`}</small><Sparkline values={values} tone={tone} /></button>
}

function LineChart({ points, labels, onClick }: { points: TrendPoint[]; labels: [string, string, string]; onClick?: () => void }) {
  const series = [points.map((point) => point.value), points.map((point) => point.secondary ?? null), points.map((point) => point.tertiary ?? null)]
  const values = series.flat().filter((value): value is number => value !== null && Number.isFinite(value)); const max = Math.max(100, ...values); const min = Math.min(0, ...values); const range = max - min || 1
  const path = (items: (number | null)[]) => items.map((value, index) => value === null ? '' : `${index === 0 || items[index - 1] === null ? 'M' : 'L'} ${24 + index / Math.max(1, items.length - 1) * 552} ${174 - (value - min) / range * 138}`).join(' ')
  return <div className="ceo-chart" onClick={onClick} role={onClick ? 'button' : undefined} tabIndex={onClick ? 0 : undefined}><div className="ceo-chart-legend">{labels.map((label, index) => <span key={label} className={`s${index + 1}`}><i />{label}</span>)}</div><svg viewBox="0 0 600 205" preserveAspectRatio="none" aria-label="趋势图"><g className="grid">{[36, 82, 128, 174].map((y) => <line key={y} x1="24" x2="576" y1={y} y2={y} />)}</g>{series.map((items, index) => <path key={labels[index]} className={`line s${index + 1}`} d={path(items)} fill="none" vectorEffect="non-scaling-stroke" />)}{points.map((point, index) => <g key={point.key}><text x={24 + index / Math.max(1, points.length - 1) * 552} y="199" textAnchor="middle">{point.label}</text>{series.map((items, seriesIndex) => items[index] === null ? null : <circle key={seriesIndex} className={`dot s${seriesIndex + 1}`} cx={24 + index / Math.max(1, points.length - 1) * 552} cy={174 - ((items[index] as number) - min) / range * 138} r="3"><title>{`${point.label} · ${labels[seriesIndex]} ${Math.round(items[index] as number)}${point.raw ? ` · ${point.raw}` : ''}`}</title></circle>)}</g>)}</svg></div>
}

function Panel({ title, action, onAction, className = '', children }: { title: string; action?: string; onAction?: () => void; className?: string; children: ReactNode }) {
  return <section className={`ceo-panel ${className}`}><header><h3>{title}</h3>{action && <button onClick={onAction}>{action} →</button>}</header>{children}</section>
}

function Empty({ text }: { text: string }) { return <p className="ceo-empty">{text}</p> }

export default function CommandCenterView({ records, onOpen, onView, onRefresh }: Props) {
  const [periodKey, setPeriodKey] = useState<CommandPeriodKey>(() => (localStorage.getItem('jason-os-command-period') as CommandPeriodKey) || '30d')
  const [customFrom, setCustomFrom] = useState(localDateKey(new Date(Date.now() - 29 * 86_400_000)))
  const [customTo, setCustomTo] = useState(localDateKey())
  const [resourceMode, setResourceMode] = useState<'time' | 'money'>('time')
  const [refreshing, setRefreshing] = useState(false)
  const [refreshedAt, setRefreshedAt] = useState(() => Date.now())
  const period = useMemo(() => resolveCommandPeriod(periodKey, new Date(), { from: customFrom, to: customTo }), [periodKey, customFrom, customTo])
  const dashboard = useMemo(() => commandCenterDashboard(records, period, new Date(refreshedAt)), [records, period, refreshedAt])
  const changePeriod = (key: CommandPeriodKey) => { setPeriodKey(key); localStorage.setItem('jason-os-command-period', key) }
  const refresh = async () => { if (refreshing) return; setRefreshing(true); try { await onRefresh(); setRefreshedAt(Date.now()) } finally { setRefreshing(false) } }
  const trendValues = dashboard.strategicTrend.map((point) => point.value ?? 0)
  const allocation = resourceMode === 'time' ? dashboard.timeAllocation : dashboard.moneyAllocation
  const allocationMax = Math.max(1, ...allocation.map((item) => item.share))
  const financeMax = Math.max(1, ...dashboard.financialTrend.flatMap((point) => [Math.abs(point.value || 0), Math.abs(point.secondary || 0), Math.abs(point.tertiary || 0)]))
  return <div className="ceo-command-center">
    <header className="ceo-command-header"><div><h2>早上好，{dashboard.profileName} <span>☀</span></h2><p>全局视角 · 关键洞察 · 决策优先</p></div><div className="ceo-command-controls"><select aria-label="统计周期" value={periodKey} onChange={(event) => changePeriod(event.target.value as CommandPeriodKey)}>{periodOptions.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select>{periodKey === 'custom' && <><input aria-label="开始日期" type="date" value={customFrom} max={customTo} onChange={(event) => setCustomFrom(event.target.value)} /><input aria-label="结束日期" type="date" value={customTo} min={customFrom} onChange={(event) => setCustomTo(event.target.value)} /></>}<span>最后更新：{new Date(dashboard.updatedAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</span><button aria-label="刷新指挥中心" disabled={refreshing} onClick={() => void refresh()}>{refreshing ? '刷新中…' : '↻'}</button></div></header>
    <div className="ceo-kpi-grid"><MetricCard metric={dashboard.kpis.goalAchievement} values={trendValues} tone="green" onClick={() => onView('outcomes')} /><MetricCard metric={dashboard.kpis.projectRisks} values={dashboard.projectPortfolio.map((item) => item.health === 'risk' ? 3 : item.health === 'attention' ? 2 : 1)} tone="orange" onClick={() => onView('projects')} /><MetricCard metric={dashboard.kpis.pendingDecisions} values={dashboard.decisionTimeline.map((_, index) => index + 1)} tone="orange" onClick={() => onView('decisions')} /><MetricCard metric={dashboard.kpis.cashResult} values={dashboard.financialTrend.map((point) => point.tertiary || 0)} tone="green" onClick={() => onView('finance')} /><MetricCard metric={dashboard.kpis.resourceEfficiency} values={dashboard.inputOutcomeTrend.map((point) => point.tertiary || 0)} tone="purple" onClick={() => onView('outcomes')} /></div>
    <div className="ceo-grid row-two"><Panel title="战略结果趋势" className="strategy"><LineChart points={dashboard.strategicTrend} labels={['目标达成率', '高于预期占比', '低于预期占比']} onClick={() => onView('outcomes')} /></Panel><Panel title="投入与结果对比" className="input"><LineChart points={dashboard.inputOutcomeTrend} labels={['时间投入指数', '资金投入指数', 'Outcome 指数']} onClick={() => onView('outcomes')} /></Panel><Panel title="CEO Attention（需重点关注）" action="查看全部" onAction={() => onView('decisions')} className="attention">{dashboard.attention.length ? <div className="ceo-attention-list">{dashboard.attention.map((item) => <button key={`${item.kind}-${item.record.id}`} onClick={() => onOpen(item.record)}><em className={item.kind}>{item.kind === 'risk' ? '高风险' : item.kind === 'deviation' ? '偏差' : item.kind === 'decision' ? '待决策' : item.kind === 'signal' ? '外部信号' : '超预算'}</em><span><strong>{item.label}</strong><small>{item.detail}</small></span></button>)}</div> : <Empty text="所选周期内没有达到 CEO Attention 阈值的事项。" />}</Panel></div>
    <div className="ceo-grid row-three"><Panel title="项目组合概览" action="查看全部" onAction={() => onView('projects')} className="portfolio">{dashboard.projectPortfolio.length ? <div className="ceo-table"><div className="head"><span>项目</span><span>健康度</span><span>目标达成率</span><span>时间投入</span><span>资金投入</span><span>趋势</span><span>风险</span></div>{dashboard.projectPortfolio.map((item) => <button key={item.record.id} onClick={() => onOpen(item.record)}><strong>{titleFor(item.record)}</strong><em className={item.health}>{item.health === 'healthy' ? '健康' : item.health === 'attention' ? '注意' : '风险'}</em><span>{item.goalAchievement === null ? '数据不足' : `${Math.round(item.goalAchievement)}%`}</span><span>{minutes(item.timeMinutes)}</span><span>{money(item.expenseMinor)}</span><Sparkline values={item.trend} tone={item.health === 'healthy' ? 'green' : 'orange'} /><em className={item.health}>{item.riskLabel}</em></button>)}</div> : <Empty text="尚无活跃项目；系统不会创建示例项目。" />}</Panel><Panel title="资源配置" className="allocation"><div className="ceo-segment"><button className={resourceMode === 'time' ? 'active' : ''} onClick={() => setResourceMode('time')}>时间投入</button><button className={resourceMode === 'money' ? 'active' : ''} onClick={() => setResourceMode('money')}>资金投入</button></div>{allocation.length ? <div className="ceo-bars">{allocation.map((item, index) => <button key={item.id} onClick={() => item.record && onOpen(item.record)}><span>{item.label}</span><i><b className={`c${index + 1}`} style={{ width: `${item.share / allocationMax * 100}%` }} /></i><strong>{Math.round(item.share)}%</strong></button>)}</div> : <Empty text={`所选周期暂无${resourceMode === 'time' ? '项目时间' : '项目资金'}记录。`} />}</Panel><Panel title="经营财务概览" action="查看财务" onAction={() => onView('finance')} className="finance"><small className="ceo-subtitle">月度联合收支趋势（近 6 个月）</small><div className="ceo-finance-trend">{dashboard.financialTrend.map((point) => <button key={point.key} title={point.raw} onClick={() => onView('finance')}><i className="income" style={{ height: `${Math.abs(point.value || 0) / financeMax * 100}%` }} /><i className="expense" style={{ height: `${Math.abs(point.secondary || 0) / financeMax * 100}%` }} /><span>{point.label}</span></button>)}</div>{dashboard.projectFinance.length ? <div className="ceo-project-finance">{dashboard.projectFinance.map((item) => <button key={item.record.id} onClick={() => onOpen(item.record)}><span>{titleFor(item.record)}</span><i><b className="income" style={{ width: `${Number(item.incomeMinor) / Math.max(1, Number(item.incomeMinor + item.expenseMinor)) * 100}%` }} /><b className="expense" style={{ width: `${Number(item.expenseMinor) / Math.max(1, Number(item.incomeMinor + item.expenseMinor)) * 100}%` }} /></i><small>{money(item.incomeMinor)} / {money(item.expenseMinor)}</small></button>)}</div> : <Empty text="没有可按项目归属的已入账流水。" />}</Panel></div>
    <div className="ceo-grid row-four"><Panel title="关键决策日历（未来 7 天）" action="查看全部" onAction={() => onView('decisions')}>{dashboard.decisionTimeline.length ? <div className="ceo-simple-list">{dashboard.decisionTimeline.map((record) => <button key={record.id} onClick={() => onOpen(record)}><time>{dueKey(record).slice(5).replace('-', '/')}</time><span><strong>{titleFor(record)}</strong><small>{String(record.expectedOutcome || record.context || '等待 CEO 决策')}</small></span><em>待决策</em></button>)}</div> : <Empty text="未来 7 天没有达到高影响门槛的待决策事项。" />}</Panel><Panel title="高影响外部信号" action="查看全部" onAction={() => onView('notebook')}>{dashboard.externalSignals.length ? <div className="ceo-simple-list signals">{dashboard.externalSignals.map((record) => <button key={record.id} onClick={() => onOpen(record)}><time>⌁</time><span><strong>{titleFor(record)}</strong><small>{String(record.summary || record.description || '已关联内部对象')}</small></span><em>高影响</em></button>)}</div> : <Empty text="所选周期没有已关联内部对象的高影响信号。" />}</Panel><Panel title="最近关键成果" action="查看全部" onAction={() => onView('outcomes')}>{dashboard.recentKeyResults.length ? <div className="ceo-simple-list results">{dashboard.recentKeyResults.map((record) => <button key={record.id} onClick={() => onOpen(record)}><time>✓</time><span><strong>{titleFor(record)}</strong><small>{String(record.summary || record.actual || '已记录结果')}</small></span><em>{resultLabel(record)}</em></button>)}</div> : <Empty text="所选周期没有已达成的战略、财务、里程碑或已核验结果。" />}</Panel></div>
  </div>
}

const resultLabel = (record: RecordData) => { const minutesValue = durationMinutes(record); return minutesValue ? minutes(minutesValue) : String(record.status || '成果') }
