import { useMemo, useState } from 'react'
import { PRODUCT_EYEBROW } from './product'
import './decisionFunnel.css'
import DecisionLogRepository from './DecisionLogRepository'
import { titleFor, type Entity, type RecordData } from './model'
import { decisionDashboard, type DecisionPeriod } from './decisionDashboard'

export type DecisionCenterTab = 'overview' | 'log'
const labels: Record<DecisionPeriod, string> = { '30d': '近30天', '90d': '近90天', quarter: '本季度', year: '今年' }
const dateLabel = (value: unknown) => { const date = value ? new Date(String(value)) : undefined; return date && !Number.isNaN(date.getTime()) ? `${date.getMonth() + 1}月${date.getDate()}日` : '—' }
const statusLabel = (value: string) => ({ PENDING: '待验证', SUPPORTED: '得到支持', PARTIALLY_SUPPORTED: '部分支持', CONTRADICTED: '被现实反驳', INCONCLUSIVE: '证据不足' }[value] || '待验证')
const levelLabel = (value: unknown) => ({ LOW: '低', MEDIUM: '中', HIGH: '高', CRITICAL: '关键' }[String(value)] || '—')
const elapsed = (value: unknown) => { const due = value ? new Date(String(value)) : undefined; if (!due || Number.isNaN(due.getTime())) return '未设置'; const days = Math.ceil((due.getTime() - Date.now()) / 86_400_000); return days < 0 ? `逾期 ${Math.abs(days)} 天` : days === 0 ? '今天到期' : `剩余 ${days} 天` }
const confidence = (decision: RecordData) => { const value = decision.confidenceAtDecision; return typeof value === 'number' || (typeof value === 'string' && value.trim()) ? `${value}%` : '—' }

function DecisionTrend({ points }: { points: Array<{ label: string; hitRate: number | null; evidenceRate: number | null }> }) {
  const path = (field: 'hitRate' | 'evidenceRate') => points.map((point, index) => { const value = point[field] ?? 0; return `${index ? 'L' : 'M'}${12 + index * 95},${127 - value * 1.03}` }).join(' ')
  return <div className="di-chart"><div className="di-legend"><span>● 决策命中率</span><span>● 已评估证据占比</span></div><svg viewBox="0 0 500 144" aria-label="决策质量趋势"><g>{[24, 50, 76, 102, 128].map((y) => <line key={y} x1="12" x2="487" y1={y} y2={y} />)}</g><path className="hit" d={path('hitRate')} /><path className="evidence" d={path('evidenceRate')} /></svg><div className="di-axis">{points.map((point) => <span key={point.label}>{point.label}</span>)}</div></div>
}

export default function DecisionIntelligenceView({ records, onOpen, onCreate, tab, onTabChange }: { records: RecordData[]; onOpen: (record: RecordData) => void; onCreate: (entity: Entity, initial?: Partial<RecordData>) => void; tab: DecisionCenterTab; onTabChange: (tab: DecisionCenterTab) => void }) {
  const [period, setPeriod] = useState<DecisionPeriod>('30d'); const [criticalAll, setCriticalAll] = useState(false); const [pendingAll, setPendingAll] = useState(false)
  const dashboard = useMemo(() => decisionDashboard(records, period), [records, period]); const funnelMax = Math.max(1, ...dashboard.funnel.map((item) => item.count)); const evidenceMax = Math.max(1, ...dashboard.evidence.map((item) => item.count))
  const metrics = [['▣', '本期重要决策', dashboard.summary.important, `${dashboard.period.label}内重要性为高/关键`, 'normal'], ['✓', '已验证决策', dashboard.summary.validated, '完成校准，不等于判断正确', 'normal'], ['◷', '待验证决策', dashboard.summary.pending, '到期且仍未完成校准', 'warning'], ['!', '高风险决策', dashboard.summary.highRisk, '仅统计人工确认的高/关键风险', 'risk'], ['◎', '决策命中率', dashboard.summary.hitRate === null ? '—' : `${dashboard.summary.hitRate}%`, dashboard.summary.hitRate === null ? '需真实结果、成功标准与校准' : `基于 ${dashboard.summary.hitCoverage} 条可比校准`, 'normal'], ['◔', '平均验证周期', dashboard.summary.averageCycleDays === null ? '—' : `${dashboard.summary.averageCycleDays} 天`, dashboard.summary.averageCycleDays === null ? '需执行与校准时间' : `基于 ${dashboard.summary.cycleCoverage} 条完整周期`, 'normal']] as const
  const newDecision = () => onCreate('decisions', { date: new Date().toISOString().slice(0, 10), status: 'pending', choiceStatus: 'PENDING', executionStatus: 'NOT_STARTED', validationStatus: 'PENDING', importance: 'MEDIUM', riskLevel: 'MEDIUM' })
  return <section className="decision-intelligence" aria-label="决策中心">
    <header className="di-head"><div className="di-title"><p className="eyebrow">{PRODUCT_EYEBROW}</p><h1>决策中心</h1><small>从问题、证据与选择，到实际结果、校准和复盘。追踪重要决策的完整生命周期。</small></div><div>{tab === 'overview' && <select aria-label="决策统计周期" value={period} onChange={(event) => setPeriod(event.target.value as DecisionPeriod)}>{(Object.keys(labels) as DecisionPeriod[]).map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select>}<button className="button primary" onClick={newDecision}>＋ 新建决策</button></div></header>
    <nav className="decision-center-tabs" aria-label="决策中心视图"><button className={tab === 'overview' ? 'active' : ''} onClick={() => onTabChange('overview')}>总览</button><button className={tab === 'log' ? 'active' : ''} onClick={() => onTabChange('log')}>决策日志</button></nav>
    {tab === 'log' ? <DecisionLogRepository records={records} onOpen={onOpen} /> : <>
      <div className="di-kpis">{metrics.map(([icon, label, value, detail, tone]) => <article className={tone} key={label}><i>{icon}</i><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
      <div className="di-row di-row-2"><section className="di-panel di-funnel"><header><div><h2>决策校准链路</h2><small>从问题到证据，从选择到真实结果和校准</small></div></header><div>{dashboard.funnel.map((item, index) => <button type="button" key={item.label} onClick={() => item.count && onOpen(dashboard.decisions.find((decision) => { if (index === 0) return Boolean(String(decision.problem || '').trim()); if (index === 1) return Boolean(String(decision.evidence || decision.evidenceSnapshot || decision.assumptions || '').trim()); if (index === 2) return Boolean(String(decision.selectedOption || decision.ceoDecision || '').trim() || decision.choiceStatus === 'DECIDED'); if (index === 3) return dashboard.resultFor(decision).length > 0; return dashboard.validation(decision) !== 'PENDING' })!)} disabled={!item.count}><i className={`stage-${index + 1}`} style={{ width: `${Math.max(25, item.count / funnelMax * 100)}%` }}>{item.label}</i><b>{item.count}</b></button>)}</div></section><section className="di-panel di-trend"><header><div><h2>决策质量趋势</h2><small>已完成校准的命中率与决策前证据评估覆盖</small></div></header><DecisionTrend points={dashboard.trend} /></section></div>
      <div className="di-row di-row-3"><section className="di-panel di-table"><header><h2>关键决策列表</h2><button onClick={() => setCriticalAll((show) => !show)}>{criticalAll ? '收起 ↑' : '查看全部 →'}</button></header>{dashboard.critical.length ? <div><div className="di-table-head critical"><span>#</span><span>决策标题</span><span>负责人</span><span>置信度</span><span>当前状态</span><span>预期影响</span></div>{dashboard.critical.slice(0, criticalAll ? undefined : 5).map((decision, index) => <button key={decision.id} onClick={() => onOpen(decision)}><b>{index + 1}</b><span>{titleFor(decision)}</span><span>{dashboard.owner(decision, dashboard.people)}</span><span>{confidence(decision)}</span><em className={dashboard.validation(decision).toLowerCase()}>{dashboard.validation(decision) === 'PENDING' ? (decision.executionStatus === 'EXECUTED' ? '待验证' : decision.choiceStatus === 'DECIDED' || decision.status === 'decided' ? '已选择' : '待选择') : statusLabel(dashboard.validation(decision))}</em><span>{dashboard.impact(decision)}</span></button>)}</div> : <p>暂无重要决策。重要性需由你在决策记录中明确确认。</p>}</section><section className="di-panel di-table"><header><h2>待校准 / 待验证</h2><button onClick={() => setPendingAll((show) => !show)}>{pendingAll ? '收起 ↑' : '查看全部 →'}</button></header>{dashboard.pending.length ? <div><div className="di-table-head pending"><span>决策标题</span><span>决策时间</span><span>验证节点</span><span>当前状态</span><span>优先级</span></div>{dashboard.pending.slice(0, pendingAll ? undefined : 5).map((decision) => <button key={decision.id} onClick={() => onOpen(decision)}><span>{titleFor(decision)}</span><span>{dateLabel(decision.decisionAt || decision.date || decision.createdAt)}</span><span>{elapsed(decision.validationDueAt || decision.reviewDueDate)}</span><em>待验证</em><span className={`di-priority ${String(decision.riskLevel || decision.importance || '').toLowerCase()}`}>{levelLabel(decision.riskLevel || decision.importance)}</span></button>)}</div> : <p>暂无具备验证条件且已到期的决策。</p>}</section></div>
      <div className="di-row di-row-4"><section className="di-panel di-evidence"><header><div><h2>证据充分度分布</h2><small>只统计人工确认的充分度，不按证据数量猜测</small></div></header>{dashboard.decisions.length ? <div>{dashboard.evidence.map((item) => <span key={item.key}><b>{item.label}</b><i><em style={{ width: `${item.count / evidenceMax * 100}%` }} /></i><strong>{item.share}% ({item.count})</strong></span>)}</div> : <p>暂无数据。创建决策后可由决策者确认当时证据充分度。</p>}</section><section className="di-panel di-misjudgments"><header><h2>误判 / 偏差复盘</h2><button onClick={() => onCreate('reviews', { title: '决策复盘', decisionErrorClassification: 'MISJUDGMENT' })}>新建复盘 →</button></header>{dashboard.misjudgments.length ? <div>{dashboard.misjudgments.slice(0, 4).map((item) => <button key={item.decision.id} onClick={() => onOpen(item.review)}><i>×</i><span><strong>{titleFor(item.decision)}</strong><small>{String(item.review.whatFailed || item.review.whyItHappened || item.review.lesson || '已确认的判断偏差')}</small></span><em>{dateLabel(item.decision.validatedAt)}</em></button>)}</div> : <p>暂无已确认的误判复盘。仅“被现实反驳”且复盘明确确认偏差的决策会出现在这里。</p>}</section><section className="di-panel di-attention"><header><h2>需 CEO 立即判断</h2><span>{dashboard.attention.length}</span></header>{dashboard.attention.length ? <div>{dashboard.attention.slice(0, 4).map((item, index) => <button key={item.id} onClick={() => onOpen(item.decision)}><b>{index + 1}</b><i className={item.severity}>{item.severity === 'high' ? '!' : '•'}</i><span><strong>{item.title}</strong><small>{item.detail}</small></span><em>{item.severity === 'high' ? '高' : '中'}</em></button>)}</div> : <p>当前暂无需要 CEO 立即判断的事项。</p>}</section></div>
      <footer className="di-foot">数据更新于 {new Date(dashboard.generatedAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })} · 所有指标只由真实 Decision、Task、Result 与 Review 记录派生</footer>
    </>}
  </section>
}
