import { useMemo, useState } from 'react'
import { titleFor, type Entity, type RecordData } from './model'
import { projectIntelligenceDashboard, type ProjectDashboardPeriod } from './projectIntelligence'

const periodLabels: Record<ProjectDashboardPeriod, string> = { month: '本月', lastMonth: '上月', '90d': '近90天', quarter: '本季度', year: '今年' }
const minutes = (value: number) => value < 60 ? `${value} 分钟` : value % 60 ? `${Math.floor(value / 60)} 小时 ${value % 60} 分钟` : `${Math.floor(value / 60)} 小时`
const healthLabel = (value: 'healthy' | 'warning' | 'blocked') => ({ healthy: '健康', warning: '关注', blocked: '受阻' }[value])
const formatDate = (value: unknown) => { const date = value ? new Date(String(value)) : undefined; return date && !Number.isNaN(date.getTime()) ? `${date.getMonth() + 1}月${date.getDate()}日` : '未设日期' }

function Sparkline() {
  return <svg className="project-sparkline empty" viewBox="0 0 80 24" aria-label="无可比历史趋势"><path d="M2,13 L78,13" /></svg>
}

export default function ProjectIntelligenceView({ records, onOpen, onSelectProject, onCreate }: { records: RecordData[]; onOpen: (record: RecordData) => void; onSelectProject: (id: string) => void; onCreate: (entity: Entity, initial?: Partial<RecordData>) => void }) {
  const [period, setPeriod] = useState<ProjectDashboardPeriod>('month')
  const dashboard = useMemo(() => projectIntelligenceDashboard(records, period), [records, period])
  const maxInvestment = Math.max(1, ...dashboard.investment.map((item) => item.minutes))
  const maxResults = Math.max(1, ...dashboard.investment.map((item) => item.results))
  const maxTrend = Math.max(1, ...dashboard.progressTrend.map((point) => point.rate || 0))
  const metrics = [
    ['◈', '活跃项目', String(dashboard.summary.active), '当前进行中或受阻项目'],
    ['!', '高风险项目', String(dashboard.summary.highRisk), dashboard.summary.highRisk ? '存在关注或受阻项目' : '当前没有风险项目'],
    ['◒', '项目进度', dashboard.summary.progressRate === null ? '—' : `${dashboard.summary.progressRate}%`, dashboard.summary.progressRate === null ? '暂无里程碑计划数据' : `${dashboard.period.label}已完成里程碑`],
    ['◷', '实际投入', minutes(dashboard.summary.totalMinutes), `${dashboard.period.label}真实时间记录`],
    ['✓', '结果产出', String(dashboard.summary.results), `${dashboard.period.label}关联 Outcome`],
    ['◎', '目标对齐率', dashboard.summary.alignmentRate === null ? '—' : `${dashboard.summary.alignmentRate}%`, dashboard.summary.alignmentRate === null ? '暂无活跃项目' : `${dashboard.summary.aligned}/${dashboard.summary.active} 项已关联目标`],
  ] as const
  return <section className="project-intelligence" aria-label="项目总览">
    <header className="project-dashboard-head"><div><p>项目健康 · 生命周期 · 投入与结果</p><small>仅基于项目、任务、里程碑、时间、成果、复盘与时间线事实派生</small></div><label className="project-period-select"><span className="sr-only">项目统计周期</span><select value={period} onChange={(event) => setPeriod(event.target.value as ProjectDashboardPeriod)}>{(Object.keys(periodLabels) as ProjectDashboardPeriod[]).map((item) => <option key={item} value={item}>{periodLabels[item]}</option>)}</select></label></header>
    <section className="project-kpi-grid">{metrics.map(([icon, label, value, meta]) => <article className={`project-kpi ${label === '高风险项目' && Number(value) > 0 ? 'risk' : ''}`} key={label}><i>{icon}</i><span>{label}</span><strong>{value}</strong><small>{meta}</small><Sparkline /></article>)}</section>
    <div className="project-dashboard-row project-health-row"><section className="project-panel project-health-panel"><header><div><h2>项目健康分布</h2><small>受阻优先于关注，关注优先于健康</small></div><span>当前 {dashboard.summary.active} 项</span></header>{dashboard.summary.active ? <div className="project-health-bars">{dashboard.health.map((item) => <button key={item.key} onClick={() => dashboard.focus.find((fact) => fact.health === item.key) && onSelectProject(dashboard.focus.find((fact) => fact.health === item.key)!.project.id)}><span>{item.label}</span><em><b className={item.key} style={{ width: `${item.count / Math.max(1, dashboard.summary.active) * 100}%` }} /></em><strong>{item.count}</strong></button>)}</div> : <p className="project-panel-empty">还没有活跃项目；创建项目后才能判断健康度。</p>}</section><section className="project-panel project-lifecycle-panel"><header><div><h2>项目生命周期漏斗</h2><small>所选周期内已记录的真实证据</small></div><span>{dashboard.period.label}</span></header>{dashboard.lifecycle.some((item) => item.count) ? <div className="project-lifecycle">{dashboard.lifecycle.map((item, index) => <button key={item.key} className={`stage-${index + 1}`} onClick={() => item.record && onSelectProject(item.record.id)} disabled={!item.record}><i style={{ width: `${Math.max(30, 100 - index * 12)}%` }} /><span>{item.label}</span><strong>{item.count}</strong></button>)}</div> : <p className="project-panel-empty">历史数据不足：尚未记录本期项目生命周期事件。</p>}</section></div>
    <div className="project-dashboard-row project-focus-row"><section className="project-panel project-focus-panel"><header><div><h2>焦点项目</h2><small>按健康风险、优先级、里程碑与本周投入排序</small></div><button onClick={() => onCreate('projects')}>＋ 新建项目</button></header>{dashboard.focus.length ? <div className="project-focus-table"><div className="project-focus-head"><span>项目</span><span>负责人</span><span>健康度</span><span>进度</span><span>本周投入</span><span>关键阻塞</span><span>下一步行动</span></div>{dashboard.focus.map((item) => <button key={item.project.id} onClick={() => onSelectProject(item.project.id)}><strong>{titleFor(item.project)}</strong><span>我</span><em className={item.health}>{healthLabel(item.health)}</em><span>{item.progress === null ? '—' : `${item.progress}%`}</span><span>{minutes(item.weeklyMinutes)}</span><span>{item.blocker || '—'}</span><span>{item.nextAction}</span></button>)}</div> : <p className="project-panel-empty">暂无焦点项目。创建项目并记录真实推进后，这里会自动排序。</p>}</section><section className="project-panel project-investment-panel"><header><div><h2>投入 vs 产出</h2><small>时间（小时）与结果（个）分别度量</small></div><span>{dashboard.period.label}</span></header>{dashboard.investment.length ? <div className="project-investment-bars">{dashboard.investment.map((item) => <button key={item.project.project.id} onClick={() => onSelectProject(item.project.project.id)}><strong>{titleFor(item.project.project)}</strong><div><i><b className="time" style={{ width: `${item.minutes / maxInvestment * 100}%` }} /></i><span>{(item.minutes / 60).toFixed(1)}h</span></div><div><i><b className="result" style={{ width: `${item.results / maxResults * 100}%` }} /></i><span>{item.results} 个</span></div></button>)}</div> : <p className="project-panel-empty">暂无活跃项目的本期投入或成果记录。</p>}</section></div>
    <div className="project-dashboard-row project-bottom-row"><section className="project-panel project-progress-panel"><header><div><h2>月度项目进度趋势</h2><small>同一里程碑口径：已完成 / 已计划</small></div><span>{dashboard.period.label}</span></header>{dashboard.progressTrend.some((item) => item.rate !== null) ? <div className="project-progress-chart"><div>{dashboard.progressTrend.map((item) => <button key={item.key} title={`${item.label}：${item.rate ?? 0}%`}><i><b style={{ height: `${(item.rate || 0) / maxTrend * 100}%` }} /></i><span>{item.label}</span><strong>{item.rate === null ? '—' : `${item.rate}%`}</strong></button>)}</div></div> : <p className="project-panel-empty">暂无里程碑计划数据，无法计算完成趋势。</p>}</section><section className="project-panel project-attention-panel"><header><div><h2>CEO Attention</h2><small>需要优先处理的项目异常</small></div><span>{dashboard.attention.length ? `${dashboard.attention.length} 项` : '正常'}</span></header>{dashboard.attention.length ? <div>{dashboard.attention.map((item) => <button key={item.id} onClick={() => onOpen(item.record)}><i className={item.severity}>{item.severity === 'high' ? '!' : '•'}</i><span><strong>{item.title}</strong><small>{item.detail}</small></span><b>›</b></button>)}</div> : <p className="project-panel-empty">当前没有达到 CEO 关注阈值的项目异常。</p>}</section><section className="project-panel project-milestones-panel"><header><div><h2>最近里程碑</h2><small>完成、临近与逾期节点</small></div><button onClick={() => onCreate('projectMilestones')}>＋ 新建</button></header>{dashboard.milestones.length ? <div>{dashboard.milestones.map(({ milestone, project, state }) => <button key={milestone.id} onClick={() => onOpen(milestone)}><i className={state}>{state === 'completed' ? '✓' : state === 'risk' ? '!' : '○'}</i><span><strong>{titleFor(milestone)}</strong><small>{project ? titleFor(project) : '未关联项目'} · {formatDate(milestone.dueDate)}</small></span><b>{state === 'completed' ? '已完成' : state === 'risk' ? '逾期' : '计划中'}</b></button>)}</div> : <p className="project-panel-empty">还没有项目里程碑。可在项目工作空间中创建并关联。</p>}</section></div>
    <footer className="project-dashboard-foot">数据更新于 {new Date(dashboard.generatedAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })} · 所有指标由本地真实记录实时派生</footer>
  </section>
}
