import { useMemo, useState } from 'react'
import { PRODUCT_EYEBROW } from './product'
import { titleFor, type Entity, type RecordData } from './model'
import { resultsIntelligence, type ResultsPeriod } from './resultsIntelligence'
import CapabilityLibrary from './CapabilityLibrary'
import './capability.css'

const labels: Record<ResultsPeriod, string> = { '7d': '近7天', '30d': '近30天', '90d': '近90天', quarter: '本季度', year: '今年' }
const dateLabel = (value: unknown) => { const date = value ? new Date(String(value)) : undefined; return date && !Number.isNaN(date.getTime()) ? `${date.getMonth() + 1}月${date.getDate()}日` : '—' }
function LineChart({ trend }: { trend: Array<{ label: string; total: number; verified: number; high: number }> }) { const max = Math.max(1, ...trend.flatMap((item) => [item.total, item.verified, item.high])); const path = (field: 'total' | 'verified' | 'high') => trend.map((item, index) => `${index ? 'L' : 'M'}${10 + index * 96},${128 - item[field] / max * 104}`).join(' '); return <div className="ri-line-chart"><div className="ri-legend"><span>● 全部成果</span><span>● 已验证</span><span>● 高价值</span></div><svg viewBox="0 0 500 145"><g>{[24, 50, 76, 102, 128].map((y) => <line key={y} x1="10" x2="490" y1={y} y2={y} />)}</g><path className="total" d={path('total')} /><path className="verified" d={path('verified')} /><path className="high" d={path('high')} /></svg><div className="ri-axis">{trend.map((item) => <span key={item.label}>{item.label}</span>)}</div></div> }

function ResultsRecords({ records, onOpen, onCreate }: { records: RecordData[]; onOpen: (record: RecordData) => void; onCreate: (entity: Entity, initial?: Partial<RecordData>) => void }) {
  const items = records.filter((record) => ['results', 'deliverables', 'resultPackages'].includes(record.entity))
  const label = (record: RecordData) => record.entity === 'results' ? '成果' : record.entity === 'deliverables' ? '成果资产' : '成果包'
  return <section className="results-records"><header><div><h2>成果记录</h2><small>结果、正式成果资产与成果包沿用现有模型，能力资产不会在此复制一份。</small></div><div><button className="button" onClick={() => onCreate('deliverables', { status: 'DRAFT', assetType: 'OTHER', versionNumber: 'v1' })}>＋ 成果资产</button><button className="button primary" onClick={() => onCreate('results', { status: 'PLANNED', outcomeType: 'QUANTITATIVE', metricKind: 'NUMBER', evidenceStatus: 'RECORDED' })}>＋ 新建结果</button></div></header>{items.length ? <div>{items.map((record) => <button key={record.id} onClick={() => onOpen(record)}><i>{record.entity === 'results' ? '✓' : record.entity === 'deliverables' ? '▣' : '▰'}</i><span><em>{label(record)}</em><strong>{titleFor(record)}</strong><small>{String(record.summary || record.status || '未填写说明')}</small></span><b>{String(record.status || '—')}</b></button>)}</div> : <p>还没有成果记录。结果可以独立存在，成果资产只关联现有文件，不复制原始文件。</p>}</section>
}

export default function ResultsIntelligenceView({ records, onOpen, onCreate, onApplyCapabilityPack, onPublishCapabilityVersion: _onPublishCapabilityVersion, onRefresh }: { records: RecordData[]; onOpen: (record: RecordData) => void; onCreate: (entity: Entity, initial?: Partial<RecordData>) => void; onApplyCapabilityPack: (pack: RecordData, projectId: string) => Promise<void>; onPublishCapabilityVersion: (asset: RecordData, version: RecordData) => Promise<void>; onRefresh: () => Promise<void> }) {
  const [period, setPeriod] = useState<ResultsPeriod>('30d'); const [tab, setTab] = useState<'overview' | 'records' | 'capabilities'>('overview'); const [moreOpen, setMoreOpen] = useState(false); const [showAllHigh, setShowAllHigh] = useState(false); const [showAllFailures, setShowAllFailures] = useState(false); const dashboard = useMemo(() => resultsIntelligence(records, period), [records, period]); const maxContribution = Math.max(1, ...dashboard.contribution.map((item) => item.total)); const maxFunnel = Math.max(1, ...dashboard.funnel.map((item) => item.count));
  const metrics = [['▣', '本期成果总数', dashboard.summary.total, `较上一期 ${dashboard.summary.previousTotal} 个`, 'normal'], ['✓', '已验证成果', dashboard.summary.verified, '仅统计有 VERIFIED 证据的成果', 'normal'], ['★', '高价值成果', dashboard.summary.high, '需用户确认 HIGH 价值分类', 'value'], ['!', '失败 / 无效成果', dashboard.summary.failed, '失败不等于待验证', 'risk'], ['▤', '成果资产化率', dashboard.summary.assetRate === null ? '—' : `${dashboard.summary.assetRate}%`, 'Final 资产 / 可沉淀成果', 'normal'], ['◷', '平均产出周期', dashboard.summary.averageCycleDays === null ? '—' : `${dashboard.summary.averageCycleDays} 天`, '仅统计有可靠周期起点的成果', 'normal']] as const
  return <section className="results-intelligence" aria-label="成果智能总览"><header className="ri-head"><div className="ri-title"><p className="eyebrow">{PRODUCT_EYEBROW}</p><h1>成果</h1><small>追踪已验证的成果、最终交付物与可沉淀的资产，帮助判断项目是否产生真实价值。</small></div><div><select aria-label="成果统计周期" value={period} onChange={(event) => setPeriod(event.target.value as ResultsPeriod)}>{(Object.keys(labels) as ResultsPeriod[]).map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select><div className="ri-more"><button type="button" aria-expanded={moreOpen} onClick={() => setMoreOpen((open) => !open)}>更多操作⌄</button>{moreOpen && <nav><button onClick={() => { setMoreOpen(false); onCreate('deliverables', { status: 'DRAFT', assetType: 'OTHER', versionNumber: 'v1' }) }}>添加成果资产</button><button onClick={() => { setMoreOpen(false); onCreate('resultPackages') }}>创建成果包</button></nav>}</div><button className="button primary" onClick={() => onCreate('results', { status: 'PLANNED', outcomeType: 'QUANTITATIVE', metricKind: 'NUMBER', evidenceStatus: 'RECORDED' })}>＋ 新建结果</button></div></header><nav className="results-tabs" aria-label="成果中心标签"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>总览</button><button className={tab === 'records' ? 'active' : ''} onClick={() => setTab('records')}>成果记录</button><button className={tab === 'capabilities' ? 'active' : ''} onClick={() => setTab('capabilities')}>能力资产</button></nav>{tab === 'overview' && <><div className="ri-kpis">{metrics.map(([icon, label, value, detail, tone]) => <article className={tone} key={label}><i>{icon}</i><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
    <div className="ri-row ri-row-2"><section className="ri-panel ri-trend"><header><h2>成果产出趋势</h2><small>按成果产生、验证及已确认价值累计</small></header><LineChart trend={dashboard.trend} /></section><section className="ri-panel ri-contribution"><header><h2>各项目成果贡献</h2><small>全部成果 / 高价值成果</small></header>{dashboard.contribution.length ? <div>{dashboard.contribution.map((item) => <button key={item.project.id} onClick={() => onOpen(item.project)}><span>{titleFor(item.project)}</span><i><b className="all" style={{ height: `${item.total / maxContribution * 100}%` }} /><b className="high" style={{ height: `${item.high / maxContribution * 100}%` }} /></i><small>{item.total} / {item.high}</small></button>)}</div> : <p>暂无可归属项目的本期成果。</p>}</section><section className="ri-panel ri-funnel"><header><h2>成果沉淀路径</h2><small>从创造到可复用的转化漏斗</small></header><div>{dashboard.funnel.map((item) => <span key={item.label}><i style={{ width: `${Math.max(28, item.count / maxFunnel * 100)}%` }}>{item.label}</i><b>{item.count}</b></span>)}</div></section></div>
    <div className="ri-row ri-row-3"><section className="ri-panel ri-table"><header><h2>高价值成果清单</h2><button onClick={() => setShowAllHigh((show) => !show)}>{showAllHigh ? '收起 ↑' : '查看全部 →'}</button></header>{dashboard.highResults.length ? <div><div className="ri-table-head"><span>#</span><span>项目</span><span>成果摘要</span><span>业务影响</span><span>验证状态</span><span>下一步</span></div>{dashboard.highResults.slice(0, showAllHigh ? undefined : 5).map((item, index) => <button key={item.id} onClick={() => onOpen(item)}><b>{index + 1}</b><span>{titleFor(dashboard.projectById.get(String(item.projectId)) || item)}</span><span>{titleFor(item)}</span><span>{dashboard.impact(item)}</span><em className={item.evidenceStatus === 'VERIFIED' ? 'verified' : ''}>{item.evidenceStatus === 'VERIFIED' ? '已验证' : '待验证'}</em><span>{String(item.nextAction || '未定义下一步')}</span></button>)}</div> : <p>没有已确认的高价值成果。</p>}</section><section className="ri-panel ri-table"><header><h2>失败 / 无效成果复盘</h2><button onClick={() => setShowAllFailures((show) => !show)}>{showAllFailures ? '收起 ↑' : '查看全部 →'}</button></header>{dashboard.failures.length ? <div><div className="ri-table-head failure"><span>#</span><span>项目</span><span>成果摘要</span><span>失败原因</span><span>发生时间</span></div>{dashboard.failures.slice(0, showAllFailures ? undefined : 5).map((item, index) => <button key={item.id} onClick={() => onOpen(item)}><b>{index + 1}</b><span>{titleFor(dashboard.projectById.get(String(item.projectId)) || item)}</span><span>{titleFor(item)}</span><span>{String(item.failureReason || item.variance || '未记录原因')}</span><span>{dateLabel(item.date || item.completedAt || item.createdAt)}</span></button>)}</div> : <p>本期没有明确标记的失败或无效成果。</p>}</section></div>
    <div className="ri-row ri-row-4"><section className="ri-panel ri-assets"><header><h2>可复用资产</h2><button onClick={() => onCreate('deliverables', { status: 'DRAFT', assetType: 'OTHER', versionNumber: 'v1' })}>查看全部 →</button></header>{dashboard.reusable.length ? <div>{dashboard.reusable.map((item, index) => <button key={item.id} onClick={() => onOpen(item)}><b>{index + 1}</b><i>▣</i><span>{titleFor(item)}<small>{String(item.assetType || 'OTHER')} · {titleFor(dashboard.projectById.get(String(item.projectId)) || item)}</small></span><em>{dateLabel(item.finalizedAt || item.updatedAt)}</em></button>)}</div> : <p>暂无 Final 正式资产；附件不等于成果资产。</p>}</section><section className="ri-panel ri-attention"><header><h2>需 CEO 关注</h2><span>{dashboard.attention.length}</span></header>{dashboard.attention.length ? <div>{dashboard.attention.map((item, index) => <button key={item.id} onClick={() => onOpen(item.record)}><b>{index + 1}</b><i className={item.severity}>{item.severity === 'high' ? '!' : '•'}</i><span><strong>{item.title}</strong><small>{item.detail}</small></span><em>{item.severity === 'high' ? '高' : '中'}</em></button>)}</div> : <p>当前没有达到 CEO 关注阈值的成果问题。</p>}</section></div><footer className="ri-foot">数据更新于 {new Date(dashboard.generatedAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })} · 指标只由 Result、Final Deliverable、Project 与证据事实派生</footer></>}{tab === 'records' && <ResultsRecords records={records} onOpen={onOpen} onCreate={onCreate} />}{tab === 'capabilities' && <CapabilityLibrary records={records} onOpen={onOpen} onApply={onApplyCapabilityPack} onRefresh={onRefresh} />}</section>
}
