import type { RecordData } from './model'

export type ResultsPeriod = '7d' | '30d' | '90d' | 'quarter' | 'year'
type Period = { start: Date; end: Date; label: string }
const failed = new Set(['FAILED', 'INVALIDATED', 'MISSED', 'ABANDONED'])
const verified = (record: RecordData) => record.evidenceStatus === 'VERIFIED'
const high = (record: RecordData) => record.valueClassification === 'HIGH'
const live = (record: RecordData) => !record.archivedAt && !record.deletedAt
const date = (value: unknown) => { const raw = typeof value === 'number' ? value : String(value || ''); const parsed = raw && /^\d+$/.test(String(raw)) ? new Date(Number(raw)) : raw ? new Date(raw) : undefined; return parsed && !Number.isNaN(parsed.getTime()) ? parsed : undefined }
const inPeriod = (value: unknown, period: Period) => { const parsed = date(value); return Boolean(parsed && parsed >= period.start && parsed <= period.end) }
const occurred = (record: RecordData) => record.date || record.completedAt || record.createdAt
const text = (value: unknown) => String(value || '').trim()
const periodFor = (preset: ResultsPeriod, now: Date): Period => { const end = new Date(now); end.setHours(23, 59, 59, 999); const start = new Date(now); const label = ({ '7d': '近7天', '30d': '近30天', '90d': '近90天', quarter: '本季度', year: '今年' } as const)[preset]; if (preset === '7d') start.setDate(start.getDate() - 6); if (preset === '30d') start.setDate(start.getDate() - 29); if (preset === '90d') start.setDate(start.getDate() - 89); if (preset === 'quarter') start.setMonth(start.getMonth() - 2, 1); if (preset === 'year') start.setMonth(0, 1); start.setHours(0, 0, 0, 0); return { start, end, label } }
const key = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`
const impact = (record: RecordData) => text(record.impact) || text(record.actual) || text(record.summary) || '已确认成果'

export function resultsIntelligence(records: RecordData[], preset: ResultsPeriod = '30d', now = new Date()) {
  const period = periodFor(preset, now); const all = records.filter(live); const results = all.filter((record) => record.entity === 'results'); const assets = all.filter((record) => record.entity === 'deliverables'); const projects = all.filter((record) => record.entity === 'projects'); const projectById = new Map(projects.map((project) => [project.id, project]));
  const reviews = all.filter((record) => record.entity === 'reviews'); const reviewedResultIds = new Set(reviews.map((review) => String(review.resultId || '')).filter(Boolean)); const finalAssetResultIds = new Set(assets.filter((asset) => asset.status === 'FINAL').map((asset) => String(asset.resultId || '')).filter(Boolean)); const current = results.filter((result) => inPeriod(occurred(result), period)); const previousDuration = period.end.getTime() - period.start.getTime(); const previous = results.filter((result) => { const point = date(occurred(result)); return Boolean(point && point >= new Date(period.start.getTime() - previousDuration - 1) && point < period.start) });
  const assetized = (result: RecordData) => finalAssetResultIds.has(result.id)
  const eligible = (result: RecordData) => ['MILESTONE', 'STRATEGIC', 'LEARNING'].includes(String(result.outcomeType)) || result.reusableCandidate === true
  const cycles = current.map((result) => { const start = date(result.cycleStartedAt); const end = date(occurred(result)); return start && end && end >= start ? (end.getTime() - start.getTime()) / 86_400_000 : undefined }).filter((value): value is number => value !== undefined)
  const trendDates = Array.from({ length: 6 }, (_, index) => { const point = new Date(period.start); point.setDate(point.getDate() + Math.round((period.end.getTime() - period.start.getTime()) / 86_400_000 / 5) * index); point.setHours(23, 59, 59, 999); return point })
  const trend = trendDates.map((point) => ({ label: `${point.getMonth() + 1}/${point.getDate()}`, key: key(point), total: results.filter((result) => { const when = date(occurred(result)); return Boolean(when && when >= period.start && when <= point) }).length, verified: results.filter((result) => { const when = date(result.validatedAt); return Boolean(when && when >= period.start && when <= point && verified(result)) }).length, high: results.filter((result) => { const when = date(occurred(result)); return Boolean(when && when >= period.start && when <= point && high(result)) }).length }))
  const contribution = [...projectById.values()].map((project) => { const items = current.filter((result) => result.projectId === project.id); return { project, total: items.length, high: items.filter(high).length } }).filter((item) => item.total).sort((a, b) => b.total - a.total || b.high - a.high).slice(0, 6)
  const created = current.length; const delivered = current.filter((result) => Boolean(result.deliveredAt || result.completedAt || ['SUCCESS', 'ACHIEVED', 'PARTIAL', 'PARTIALLY_ACHIEVED'].includes(String(result.status)))).length; const validated = current.filter(verified).length; const assetizedCount = current.filter((result) => assetized(result)).length
  const highResults = current.filter(high).sort((a, b) => Number(verified(b)) - Number(verified(a)) || String(b.updatedAt).localeCompare(String(a.updatedAt)))
  const failures = current.filter((result) => failed.has(String(result.status))).sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)))
  const reusable = assets.filter((asset) => asset.status === 'FINAL').sort((a, b) => String(b.finalizedAt || b.updatedAt).localeCompare(String(a.finalizedAt || a.updatedAt))).slice(0, 5)
  const attention = [...projectById.values()].flatMap((project) => { const items = current.filter((result) => result.projectId === project.id); const highUnverified = items.filter((result) => high(result) && !verified(result)); const unreviewedFailures = items.filter((result) => failed.has(String(result.status)) && !reviewedResultIds.has(result.id)); const eligibleUnassetized = items.filter((result) => eligible(result) && !assetized(result)); const issue = highUnverified.length ? { id: `unverified-${project.id}`, severity: 'high' as const, title: `${title(project)} 有 ${highUnverified.length} 个高价值成果待验证`, detail: '高价值需要证据或正式验证，不能仅按完成状态确认。', record: highUnverified[0] } : unreviewedFailures.length ? { id: `failed-${project.id}`, severity: 'high' as const, title: `${title(project)} 有 ${unreviewedFailures.length} 个失败 / 无效成果待复盘`, detail: '请记录失败原因，并通过复盘确认后续处理方式。', record: unreviewedFailures[0] } : eligibleUnassetized.length >= 2 ? { id: `assets-${project.id}`, severity: 'medium' as const, title: `${title(project)} 有 ${eligibleUnassetized.length} 个成果尚未资产化`, detail: '符合沉淀资格的成果还未关联 Final 正式资产。', record: eligibleUnassetized[0] } : null; return issue ? [issue] : [] }).sort((a, b) => Number(b.severity === 'high') - Number(a.severity === 'high')).slice(0, 5)
  return { period, generatedAt: now.toISOString(), summary: { total: created, verified: validated, high: current.filter(high).length, failed: failures.length, assetRate: current.filter(eligible).length ? Math.round(assetizedCount / current.filter(eligible).length * 100) : null, averageCycleDays: cycles.length ? Math.round(cycles.reduce((sum, value) => sum + value, 0) / cycles.length * 10) / 10 : null, previousTotal: previous.length }, trend, contribution, funnel: [{ label: '草稿成果', count: created }, { label: '已交付', count: delivered }, { label: '已验证', count: validated }, { label: '资产化', count: assetizedCount }], highResults, failures, reusable, attention, projectById, assetized, impact }
}
const title = (record: RecordData) => text(record.title) || '未命名项目'
